#Application Name
spring:
  application:
    name: auth-server 
    
#Cassandra DB     
---
spring:
  data:
    cassandra:
      cluster-name: My Cluster
      contact-points: 35.244.42.148
      keyspace-name: vault
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
      consistency-level: ONE
      connect-timeout: 10000ms
      read-timeout: 10000ms
      pool:
        pool-timeout: 10000ms
  main:
    allow-bean-definition-overriding: true      

#Server Port
server:
  port: 9100
  

# Application Business Properties
records: 
  max-limit: 100
  initial-count: 20
  page-no: 0
  
# Cassandra Query Logger
logging.level.com.datastax.driver.core.QueryLogger.NORMAL: DEBUG
    
    
# Logging
logging:
  level:
    com:
      hackpro:
        authserver: debug
    # org.springframework: debug
    # org.springframework.security: error   